name = "ung-cyber-unit-website"
main = "worker.js"
compatibility_date = "2024-01-01"

[assets]
directory = "./public"
binding = "ASSETS"
run_worker_first = true

[[d1_databases]]
binding      = "DB"
database_name = "cyber-unit-db"
database_id  = "30fcf0cc-9912-430e-a8d2-54b9dec9ba1a"
